import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import '../secrets/constants.dart';

class Auth with ChangeNotifier {
  String
      _token; //this is a temporary token variable that holds the token generated by the backend, in our case, firebase.
  DateTime _expiryDate; //stores the expiry DateTime
  String _userId;

  //method used to sign the user up

  Future<void> _authenticate(
      String email, String password, String urlPart) async {
    //for info - https://firebase.google.com/docs/reference/rest/auth/
    final url = Uri.https(
        'identitytoolkit.googleapis.com', 'v1/accounts:$urlPart', A.param);
    final response = await http.post(
      url,
      body: json.encode(
        {'email': email, 'password': password, 'returnSecureToken': true},
      ),
    );
    print(json.decode(response.body));
  }

  Future<void> signup(String email, String password) async {
    await _authenticate(email, password, 'signUp');
  }

  Future<void> login(String email, String password) async {
    await _authenticate(email, password, 'signInWithPassword');
  }
}
